server:
  port: 30000
spring:
  application:
    name: sxx-service-home
  datasource:
    url: jdbc:mysql://52.83.149.232:3306/sxx?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: sxxpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://www.sixuexing.com:50101/eureka/,http://www.sixuexing.com:50102/eureka/}
  instance:
    prefer‐ip‐address: true #将自己的ip地址注册到Eureka服务中
    ip‐address: ${IP_ADDRESS:127.0.0.1}
    instance‐id: ${spring.application.name}:${server.port} #指定实例id
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true # 开启驼峰命名转换法
pagehelper:
  helper-dialect: mysql